const user = {
    login: "mcelroyian",
    id: 937995,
    url: "https://api.github.com/users/mcelroyian",
    html_url: "https://github.com/mcelroyian",
    followers_url: "https://api.github.com/users/mcelroyian/followers",
    following_url: "https://api.github.com/users/mcelroyian/following{/other_user}",
    name: "Ian McElroy",
    location: "Wiggins, Ms",
    email: null,
    hireable: null,
    bio: "Full Stack Web Developer",
    followers: 21,
    following: 26,
  }